/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CoachBookking;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asus
 */
public class Adminpanel extends javax.swing.JFrame {

    /**
     * Creates new form Adminpanel
     */
    public Adminpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtR_id = new javax.swing.JTextField();
        txtSt_Id = new javax.swing.JTextField();
        txtDest_Id = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPrice_Id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        view_tab = new javax.swing.JTable();
        btnview = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnadd_admin = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel1.setText("Admin Panel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 91, 28));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel2.setText("Route_ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 100, 119, 30));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel3.setText("Starting_Point");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 148, 119, 30));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel4.setText("Destination_Point");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 205, 119, 30));

        txtR_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtR_idActionPerformed(evt);
            }
        });
        getContentPane().add(txtR_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 100, 163, 30));

        txtSt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSt_IdActionPerformed(evt);
            }
        });
        getContentPane().add(txtSt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 148, 163, 30));

        txtDest_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDest_IdActionPerformed(evt);
            }
        });
        getContentPane().add(txtDest_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 205, 163, 30));

        btnsearch.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search_32.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 386, -1, -1));

        btnedit.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit2_32.png"))); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 386, 100, -1));

        btndelete.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete_32.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 386, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 324, 93, 30));

        txtPrice_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrice_IdActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrice_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 324, 163, 30));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 267, 119, 30));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 267, 163, 30));

        view_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Route_ID", "Starting_Point", "Destination_Point", "Date", "Price"
            }
        ));
        jScrollPane2.setViewportView(view_tab);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 860, 530));

        btnview.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/view_32.png"))); // NOI18N
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 100, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/address_32.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 100, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/date_32.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 267, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/price_32.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 324, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/start_32.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 148, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/route_32.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 205, -1, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnadd.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add2_32.png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnadd_admin.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnadd_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/admin_32.png"))); // NOI18N
        btnadd_admin.setText("New Admin");
        btnadd_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnadd)
                .addContainerGap(508, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnadd_admin))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addComponent(btnadd)
                .addGap(63, 63, 63)
                .addComponent(btnadd_admin))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtR_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtR_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtR_idActionPerformed

    private void txtSt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSt_IdActionPerformed

    private void txtDest_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDest_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDest_IdActionPerformed

    private void txtPrice_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrice_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice_IdActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String Route_id, Start_point , Destination_point , Date , Price;
        Route_id =txtR_id.getText();
        Start_point=txtSt_Id.getText();
        Destination_point = txtDest_Id.getText();
        Date=txtDate.getText();
        Price=txtPrice_Id.getText();
        
        Connector N = new Connector();
        Connection C =N.connect();
        
        try{
        Statement S = C.createStatement();
        int A = S.executeUpdate("INSERT INTO ADMIN VALUES('"+Route_id+"','"+Start_point+"','"+Destination_point+"','"+Date+"','"+Price+"')");
        if(A==1)
            {
            JOptionPane.showMessageDialog(null, "Successfully Added");
            }
        
        }
        
        catch(SQLException m)
        {}
    }//GEN-LAST:event_btnaddActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
       try{
        String Route_id, Start_point , Destination_point , Date , Price;
        ResultSet R;
        Route_id =txtR_id.getText();
        Start_point=txtSt_Id.getText();
        Destination_point = txtDest_Id.getText();
        Date=txtDate.getText();
        Price=txtPrice_Id.getText();
        
        Connector N = new Connector();
        Connection C =N.connect();
        
        Statement S=C.createStatement();
        R=S.executeQuery("SELECT ROUTE_ID ,START_POINT,DESTINATION_POINT,DATE ,PRICE FROM ADMIN");
        boolean x=false;
        while(R.next())
            {
            if(Route_id.equals(R.getString(1)))
                {
                 S.executeUpdate("UPDATE TABLE ADMIN SET PRICE='"+Price+"' , START_POINT='"+Start_point+"',DESTINATION_POINT='"+Destination_point+"' AND DATE_='"+Date+"' WHERE ROUTE_ID='"+Route_id+"'");
                 x=true;
                }
            }
        if(x==false)
            {
            JOptionPane.showMessageDialog(null,"Retype The Route_ID Correctly");
            }
        else
            {
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            }
       }
       
       catch(SQLException S){
       
       }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
         try{
        String Route_id, Start_point , Destination_point , Date , Price;
        ResultSet R;
        Connector N = new Connector();
        Connection C =N.connect();
        Statement S=C.createStatement();
        R=S.executeQuery("SELECT * FROM ADMIN WHERE ROUTE_ID='"+txtR_id.getText()+"'");
        if(R.next())
        {
        Route_id =R.getString("ROUTE_ID");
        txtR_id.setText(Route_id);
        Start_point =R.getString("START_POINT");
        txtSt_Id.setText(Start_point);
        Destination_point =R.getString("DESTINATION_POINT");
        txtDest_Id.setText(Destination_point);
        Date =R.getString("DATE_");
        txtDate.setText(Date); 
        Price =R.getString("PRICE");
        txtPrice_Id.setText(Price);
        }
         }
         catch(SQLException S){}
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try{
        Connector N = new Connector();
        Connection C =N.connect();
        Statement S=C.createStatement();
       int  R=S.executeUpdate("DELETE * FROM ADMIN WHERE ROUTE_ID='"+txtR_id.getText()+"'");
       if(R==1)
       {
       JOptionPane.showMessageDialog(null,"Successfully Deleted");
       }
        }
         catch(SQLException S){}
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        try{
        Connector N = new Connector();
        Connection C =N.connect();
        Statement S=C.createStatement();
        ResultSet R;
        R=S.executeQuery("SELECT * FROM ADMIN");
        
        view_tab.setModel(DbUtils.resultSetToTableModel(R));
        
        
        }
         catch(SQLException S){}
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnadd_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_adminActionPerformed
        Admin_SignUp A = new Admin_SignUp();
        A.setVisible(true);
    }//GEN-LAST:event_btnadd_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd_admin;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDest_Id;
    private javax.swing.JTextField txtPrice_Id;
    private javax.swing.JTextField txtR_id;
    private javax.swing.JTextField txtSt_Id;
    private javax.swing.JTable view_tab;
    // End of variables declaration//GEN-END:variables
}
